# Generated by Django 5.1.3 on 2024-12-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_classificacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classificacao",
            old_name="notas",
            new_name="nota",
        ),
    ]
